Test

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -67,22 +67,27 @@ jobs:
         echo "$PRIVATE_KEY" | base64 --decode > github-ec2.pem
         chmod 600 github-ec2.pem
 
-        # Verify if the key is correctly formatted
-        ssh-keygen -y -f github-ec2.pem > /dev/null || { echo "Invalid private key!"; exit 1; }
+        # # Verify if the key is correctly formatted
+        # ssh-keygen -y -f github-ec2.pem > /dev/null || { echo "Invalid private key!"; exit 1; }
+
+        # Upload docker-compose.yml and nginx.conf using SCP
+        scp -o StrictHostKeyChecking=no -i github-ec2.pem docker-compose.yml ${USER}@${HOST}:/home/ubuntu/iot-server/
+        scp -o StrictHostKeyChecking=no -i github-ec2.pem nginx.conf ${USER}@${HOST}:/home/ubuntu/iot-server/
 
         # SSH into EC2
         ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} << 'EOF'
           echo "Current directory: $(pwd)"
           echo "Listing home directory:"
+          cd /home/ubuntu/iot-server/
           ls -la ~
         EOF
 
-    - name: Upload Files to EC2
-      run: |
-        scp -o StrictHostKeyChecking=no \
-          docker-compose.yml \
-          nginx.conf \
-          ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/iot-server/
+    # - name: Upload Files to EC2
+    #   run: |
+    #     scp -o StrictHostKeyChecking=no \
+    #       docker-compose.yml \
+    #       nginx.conf \
+    #       ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/iot-server/
 
     # - name: SSH into EC2 and Deploy Updates
     #   uses: appleboy/ssh-action@v0.1.6
